# Generated by Django 2.2.4 on 2019-08-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaintdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mob', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('imgid', models.CharField(max_length=100)),
            ],
        ),
    ]
